name: ivpn_new
description: iVPN Client - High Performance VPN
version: 1.0.0+1771954304

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Networking & API
  html: ^0.15.4
  dio: ^5.7.0
  http: ^1.2.2
  connectivity_plus: ^6.1.0

  # UI & State Management
  provider: ^6.1.2
  window_manager: ^0.4.3
  webview_flutter: ^4.9.0
  webview_windows: ^0.4.0
  flutter_markdown: ^0.7.4 # اضافه شد برای رفع ارور دیالوگ آپدیت

  # Media & Ads
  video_player: ^2.8.6
  chewie: ^1.8.1
  cached_network_image: ^3.3.1
  logger: ^2.2.0

  # Utilities & Storage
  path_provider: ^2.1.5
  path: ^1.9.0
  file_picker: ^8.1.4
  device_info_plus: ^11.1.0
  url_launcher: ^6.3.1
  shared_preferences: ^2.3.2
  crypto: ^3.0.5
  package_info_plus: ^8.0.0
  pub_semver: ^2.1.4
  permission_handler: ^11.3.1
  collection: ^1.17.0
  
  # File Opening (Fixed for Android)
  open_file: ^3.5.10 # جایگزین نسخه Plus شد

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.2
  flutter_lints: ^5.0.0
  build_runner: ^2.4.13
  mockito: ^5.4.4
  
  # Build Script Requirements (حیاتی برای setup_core.dart)
  archive: ^3.6.1
  mocktail: ^1.0.4
  webview_flutter_platform_interface: ^2.9.0

# تنظیمات آیکون
flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/icon.png"
  windows:
    generate: true
    image_path: "assets/icon.png"
    icon_size: 48

flutter:
  uses-material-design: true
  assets:
    - assets/icon.png
    # Windows Assets
    - assets/executables/windows/sing-box.exe
    - assets/executables/windows/geoip.db
    - assets/executables/windows/geosite.db
    # Generic Assets
    - assets/geoip.db
    - assets/geosite.db
    - assets/html/
