name: ivpn_new
description: IVPN Client with Advanced Testing
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.0.0

  # UI & State
  provider: ^6.0.5
  flutter_launcher_icons: ^0.13.1

  # Networking
  http: ^1.1.0
  connectivity_plus: ^4.0.2

  # Utilities
  crypto: ^3.0.3
  shared_preferences: ^2.2.2
  file_picker: ^6.1.1
  path_provider: ^2.1.0
  path: ^1.8.3
  url_launcher: ^6.2.1
  device_info_plus: ^10.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icon.png
    - assets/executables/windows/sing-box.exe
